### PR TITLE
External IP Addresses Used by the MPTCP Proxy

### PR DESCRIPTION
**Pull request by boucadair**

### CODE REVIEW

**Comment by obonaventure** [comment]
I would suggest to keep this part as simple as possible

**Comment by boucadair** [comment]
> 
> 
> I would suggest to keep this part as simple as possible

Please check d516376 and let me know if you we need to simplify further.

**Comment by obonaventure** [comment]
I'm fine to include this revision if others agree

**Review by mpiraux — APPROVED** [review]

**Review by mirjak — CHANGES_REQUESTED** [review]
This probably doesn't merge properly anymore but I think we should have this text. I would recommend to have it as part of the overview section and remove MPTCP specific language (s/MPTCP Proxy/Proxy/).

**Comment by boucadair** [comment]
> 
> 
> This probably doesn't merge properly anymore but I think we should have this text. I would recommend to have it as part of the overview section and remove MPTCP specific language (s/MPTCP Proxy/Proxy/).

Works for me. Fixed in c535be9.

**Comment by mpiraux** [comment]
Could you fix the conflict and place it appropriately so that we can merge the text ? Thanks.

**Comment by boucadair** [comment]
> 
> 
> Could you fix the conflict and place it appropriately so that we can merge the text ? Thanks.

Done.

**Pull request merged**
