### PR TITLE
Move text to the ATSSS rules section

### PR DESCRIPTION
**Pull request by boucadair**

### CODE REVIEW

**Comment by mpiraux** [comment]
This text is better placed in the ATSSS rules section indeed. But now the ref architecture figure mentions ATSSS rules, and no text exists to explain at least that we discuss them later.
How about:

> The 5G control plane provides the UE and the Proxy with ATSSS rules, which are described in Section XYZ

**Comment by boucadair** [comment]
> 
> 
> This text is better placed in the ATSSS rules section indeed. But now the ref architecture figure mentions ATSSS rules, and no text exists to explain at least that we discuss them later.
> How about:
> 
> > The 5G control plane provides the UE and the Proxy with ATSSS rules, which are described in Section XYZ

Fair. Fixed.

**Comment by mpiraux** [comment]
I might have been unclear, but I was thinking about the other way around, i.e. referencing ATSSS rules from the Reference Architecture section. Do you still agree?

**Comment by boucadair** [comment]
> 
> 
> I might have been unclear, but I was thinking about the other way around, i.e. referencing ATSSS rules from the Reference Architecture section. Do you still agree?

This is better given the new text addition.

**Comment by mirjak** [comment]
WFM.

**Pull request merged**
