### PR TITLE
Restructure ATSSSv2 Section

### PR DESCRIPTION
**Pull request by boucadair**
Some notes: 
* The text may be interpreted as if we are "promoting" solutions rather than explaining the technical issues.
* We might add a discussion on QUIC and non-QUIC traffic and further explain that even for the QUIC case, there is a gap that needs to be filled.
* Some of the complications are induced by the desire to support of TCP. I suggest to put those at the end of the section.

### CODE REVIEW

**Comment by markusa** [comment]
Hi Med,

I support your PR. However I'm wondering if we should be a little bit more transparent and elaborate  (maybe not in the same depth than QUIC) other potential solutions (SCTP/MP-DCCP).

For the sake of the 3GPP timeline, I could imagine that it might be interesting for 3GPP to learn about other solutions. In case the QUIC roadmap does not develop accordingly or cannot keep the timeline, alternatives could come in focus.

**Comment by obonaventure** [comment]
Hi Markus,

I think the document should focus on what 3GPP SA2 expects from the IETF. This is more an input to the IETF (and in particular the QUIC WG) than an input to 3GPP. I agree that SCTP and MP-DCCP could also be used to provide the ATSSS service, but those proposals should be discussed in a separate document.

**Comment by markusa** [comment]
Hi Olivier,

not sure on that. I agree, that the LS requested primarily QUIC. But my expectation is, that the draft where we work on, becomes a linking document between 3GPP and IETF. In that respect I think it is fair to raise issues which probably prevent Rel. 17 usage of QUIC and mention potential alternatives. All this with the aim to ensure non-TCP support within Rel. 17 timeframe.

I'm happy to get further opinions here.

**Comment by mirjak** [comment]
I support to have TCP over a QUIC tunnel in a separate section, however, this PR makes a bunch of changes (and is therefore hard to oversee) and might remove too much of the text. Especially the point that some end-to-end traffic is tunnelled over a QUIC connection between the UE and the ATSSS node might have gotten lost but should be there at the very beginning. Maybe you can split this PR up in to a set of smaller PRs?

**Comment by obonaventure** [comment]
Since the PR is huge and difficult to discuss, I have approved it to generate a new version which can then be updated by others.

**Pull request merged**
