### PR TITLE
Update draft-quic-atsss-reqs.mkd to add simplified reference architecture diagram

### PR DESCRIPTION
**Pull request by SpencerDawkins**
Add simplified reference architecture diagram

### CODE REVIEW

**Comment by obonaventure** [comment]
I had something similar in mind but could not finalise it yet:


The ATSSS service is defined several 3GPP documents that reference several
other documents. A detailed presentation of this service is outside the
scope of this section.

To understand the operation of the ATSSS service, it is useful to consider the
reference environment shown in the figure below. A host, called A in the
figure, is attached to two different access networks (Net1 and Net2).
These networks can be managed by different organizations.
A second host, called B in the figure, 
is connected to the Internet. B does not use multipath transport protocols
while A would like to be able to use its two access networks to reach B. To
enable A to use its two paths efficiently, a possible solution is to use
a midpoint node, called M in the figure, so that multipath transport is
used between A and M while regular (single path) transport is used
between A and B. 

~~~~~~~~~~~~~~~~~~~~~~~~~~~

  +------ Net 1 ------+
  |                   |
+-+-+               +-+-+                     +---+
| A |               | M |----- Internet  -----+ B |
+-+-+               +-+-+                     +---+
  |                   |
  +------ Net 2 ------+
~~~~~~~~~~~~~~~~~~~~~~~~~~~
{: #fig-env title="Reference environment"}


Several use cases correspond to this environment. A first use case are the
mobile devices like smartphones that are equipped with a cellular and
a Wi-Fi interface.
A second use case are the hybrid access networks where A is a CPE router that
is attached to fixed (e.g. xDSL) and wireless (e.g. cellular) networks.

In this document, we focus on the first use case, but most of the discussion
applies to the second one as well.

The two scenarios that we consider in this document are:
- the failure of one access network that forces all data to switch to the other access network
- the possibility of splitting the transmission of the data over the two access networks even if they have different characteristics (delay, bandwidth, congestion)

**Comment by obonaventure** [comment]
Here is Med's proposal 👍 
 
~~~~~~~~~~~~~~~
               +---------+           +-------+      +------+

     +---------+   AMF   +--- N11 ---+  SMF  +- N7 -+  PCF |

     |         ++--+-----+           +---+---+      +------+

     |          |  |                     |             

     |          |  |                     |

     N1         N2 N2                    N4

     |          |  |                     |

  +--+--+       | ++-----------+      +---+---+        +------+

  |  UE +---------+ 3GPP Access+- N3 -+  UPF  +-- N6 --+  DN  |

  |MPTCP|       | +------------+      |       |        +------+

  |     |     +-+----------+          | MPTCP |

  |     +-----+  Non-3GPP  +---- N3 --+ Proxy |

  |ATSSS|     |   Access   |          |       |

  | LL  |     +------------+          |  PMF  |

  +-----+                             +-------+

 ~~~~~~~~~

We can then indicate briefly in the text how steering polices are communicated to the UE/UPF + role of PMF + discovery of the proxy by the UE. Then, clearly state that all the control part is out of scope. Finlay, we can zoom on the data plane part (your figure).

**Comment by obonaventure** [comment]
I would suggest to avoid using any 3GPP specific names because I fear that IETFers will be surprised by this terminology

**Comment by boucadair** [comment]
> 
> 
> I would suggest to avoid using any 3GPP specific names because I fear that IETFers will be surprised by this terminology

I suspect that as well but I think that we need to include a minimum to introduce the ATSSS reference architecture as specified by the 3GPP. Then, we can generalize the problem space using the figure provided by Spencer or yours.

**Comment by TimCostello** [comment]
I like the high level pictures, they do a good job of showing the problem that ATSSS is trying to solve before going in to the detail of 3GPP names.

**Comment by mpiraux** [comment]
There seems to be consensus on trying to avoid 3GPP names in the overview. I see a question emerging: should we adopt a more abstract description (i.e. not mentioning MPTCP), as proposed by Olivier, or explicitly mention MPTCP as proposed in this PR ?

I will turn Olivier's proposal in a separate PR so that we discuss and comment it properly.

**Comment by mpiraux** [comment]
Nevermind, Olivier's proposal is actually part of the text in the master branch.

**Pull request merged**
