### PR TITLE
Multipath-Specific Addressing

### PR DESCRIPTION
**Pull request by boucadair**

### CODE REVIEW

**Review by SpencerDawkins — COMMENTED** [review]
How critical is this terminology? Am I understanding that it's not taken from https://www.rfc-editor.org/rfc/rfc8684.html?

My concern is that we're going to need a translation table from 3GPP-speak to IETF-speak, and that's not going to help us motivate IETF people. Thoughts?

**Comment by boucadair** [comment]
No, these addresses are not taken from rfc8684. 

I don't like the "link-*" terminology used by the 3GPP, this is why I have a note to avoid confusion with link-scoped prefixes. 

The key point is that a terminal is assigned three @/prefixes; two of them are bound to each of the access networks. 

Having a name for these addresses is useful to distinguish it from the third address/prefix. Will think about how to tweak this.

**Comment by mpiraux** [comment]
Will this particular addressing translate to a particular requirement in the future versions of this document ? More text explaining what this particularity imposes would help me to understand why we need this level of details.

**Comment by boucadair** [comment]
> Will this particular addressing translate to a particular requirement in the future versions of this document ? More text explaining what this particularity imposes would help me to understand why we need this level of details.

Likely, but we are not at drafting requirements yet!
The agreement is to have an overview of how ATSSS works. I'm not planning to add more text as the key information is already captured in this PR.

**Pull request merged**
