### PR TITLE
Some issues with solutions relying on a single connection

### PR DESCRIPTION
**Pull request by boucadair**

### CODE REVIEW

**Review by obonaventure — CHANGES_REQUESTED** [review]
There are other issues that we can probably discuss concerning the utilisation of 2 QUIC connections to transport datagrams over a congestion-controlled flow. Here is some information, let me know if you agree.

- the two QUIC connections are throttled by their congestion control scheme, which means that the available bandwidth on each will vary over time. It will be difficult for an application that manages them in real-time to schedule packets while the scheduler included inside Multipath QUIC would have access to the congestion control information
- if one of the QUIC connections suffers from a much longer latency than the other, it will be difficult for an application that uses them to detect this problem without using application-level rat measurements. Multipath QUIC carries these measurements automatically.
- if one of the QUIC connections is lossy, e.g. when a UE moves out of the reach of one access network, an application managing them would not be able to detect this problem unless it includes its own acknowledgements or loss measurements. Multipath QUIC includes loss detection techniques.

Concerning the battery consumption, we could say something like:

Like Multipath TCP, Multipath QUIC supports make-before-break and break-before-make. The latter enables the UE to activate the second access network only when needed. While MPTCP requires a full handshake before using a new path, MPQUIC is faster.

**Comment by boucadair** [comment]
> Concerning the battery consumption, we could say something like:
> 
> Like Multipath TCP, Multipath QUIC supports make-before-break and break-before-make. The latter enables the UE to activate the second access network only when needed. While MPTCP requires a full handshake before using a new path, MPQUIC is faster

Olivier, I'm not sure this text is related to the battery consumption. 

Also, this text does not belong to the single connection. You can add it into the "MP-QUIC tunneling" section. Below a suggested rewording to present this as a requirement:

NEW:
Like Multipath TCP, Multipath QUIC should support make-before-break and break-before-make. The latter enables the UE to activate the second access network only when needed. While MPTCP requires a full handshake before using a new path, MPQUIC is faster.

**Comment by boucadair** [comment]
>     * if one of the QUIC connections suffers from a much longer latency than the other, it will be difficult for an application that uses them to detect this problem without using application-level rat measurements. Multipath QUIC carries these measurements automatically.

For this one, the UE can rely on the PMF measurements. So, I don't think this is an issue for ATSSS.

I agree with your point if no similar PMF functionality is available.

**Comment by boucadair** [comment]
> * the two QUIC connections are throttled by their congestion control scheme, which means that the available bandwidth on each will vary over time. It will be difficult for an application that manages them in real-time to schedule packets while the scheduler included inside Multipath QUIC would have access to the congestion control information
> 
> 
> * if one of the QUIC connections is lossy, e.g. when a UE moves out of the reach of one access network, an application managing them would not be able to detect this problem unless it includes its own acknowledgements or loss measurements. Multipath QUIC includes loss detection techniques.

I agree with these two.

**Comment by boucadair** [comment]
Olivier, I let you propose a PR with the points you suggested. Thanks.

**Pull request closed without merging**
